export const activeStudents = [
  {
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "9876543210",
    course: "Web Development",
    status: ["online", "offline"],
    enrollmentDate: "15-01-24",
  },
  {
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "8765432109",
    course: "Data Science",
    status: ["offline", "online"],
    enrollmentDate: "10-12-23",
  },
  {
    name: "Robert Johnson",
    email: "robert.j@example.com",
    phone: "7654321098",
    course: "Cybersecurity",
    status: ["online", "offline"],
    enrollmentDate: "22-03-24",
  },
  {
    name: "Emily Davis",
    email: "emily.d@example.com",
    phone: "6543210987",
    course: "AI and Machine Learning",
    status: ["offline", "online"],
    enrollmentDate: "30-11-23",
  },
  {
    name: "Michael Brown",
    email: "michael.b@example.com",
    phone: "5432109876",
    course: "Cloud Computing",
    status: ["online", "offline"],
    enrollmentDate: "18-02-24",
  },
  {
    name: "Sarah Wilson",
    email: "sarah.w@example.com",
    phone: "4321098765",
    course: "Software Engineering",
    status: ["offline", "online"],
    enrollmentDate: "05-01-24",
  },
  {
    name: "David Lee",
    email: "david.l@example.com",
    phone: "3210987654",
    course: "Mobile App Development",
    status: ["online", "offline"],
    enrollmentDate: "28-02-24",
  },
  {
    name: "Sophia Martinez",
    email: "sophia.m@example.com",
    phone: "2109876543",
    course: "Blockchain",
    status: ["offline", "online"],
    enrollmentDate: "15-12-23",
  },
  {
    name: "Alice Brown",
    email: "alice.b@example.com",
    phone: "9876541230",
    course: "Web Development",
    status: ["online", "offline"],
    enrollmentDate: "12-01-24",
  },
  {
    name: "Tom Parker",
    email: "tom.p@example.com",
    phone: "8765432190",
    course: "Full Stack Development",
    status: ["offline", "online"],
    enrollmentDate: "20-01-24",
  },
  {
    name: "Natalie Green",
    email: "natalie.g@example.com",
    phone: "7654321980",
    course: "Web Development",
    status: ["online", "offline"],
    enrollmentDate: "25-01-24",
  },
  {
    name: "Jack Taylor",
    email: "jack.t@example.com",
    phone: "6543219870",
    course: "Full Stack Development",
    status: ["offline", "online"],
    enrollmentDate: "15-02-24",
  },
  {
    name: "Emma White",
    email: "emma.w@example.com",
    phone: "5432198760",
    course: "Web Development",
    status: ["online", "offline"],
    enrollmentDate: "10-02-24",
  },
  {
    name: "Oliver Harris",
    email: "oliver.h@example.com",
    phone: "4321987650",
    course: "Full Stack Development",
    status: ["offline", "online"],
    enrollmentDate: "05-02-24",
  },
  {
    name: "Mia Scott",
    email: "mia.s@example.com",
    phone: "3219876540",
    course: "Web Development",
    status: ["online", "offline"],
    enrollmentDate: "18-01-24",
  },
  {
    name: "Lucas Evans",
    email: "lucas.e@example.com",
    phone: "2198765430",
    course: "Full Stack Development",
    status: ["offline", "online"],
    enrollmentDate: "28-01-24",
  },
];



export const courseCategories = [
  // {
  //   name:"Choose A Course"
  // },
  {
    name: "All",
  },
  {
    name: "Web Development",
  },
  {
    name: "Full Stack Development",
  },
  {
    name: "	Data Science",
  },
  {
    name: "Cybersecurity Essentials",
  },
  {
    name: "AI and Machine Learning Fundamentals",
  },
  {
    name: "Web Development with React",
  },
  {
    name: "Blockchain Basics",
  },
  {
    name: "Cloud Computing Masterclass",
  },
  {
    name: "Mobile App Development with Flutter",
  },
  {
    name: "Software Engineering Principles",
  },
  {
    name: "DevOps for Beginners",
  },
];


export const studentPurchaseDataSample = [
  {
    id: "64b9ee9f1c4e88f1a2b5c123",
    trackingId: "TRK123456",
    customerName: "John Doe",
    email: "john.doe@example.com",
    amount: 1200,
    paymentMode: "Credit Card",
    status: "Success",
  },
  {
    id: "64b9ee9f1c4e88f1a2b5c124",
    trackingId: "TRK123457",
    customerName: "Jane Smith",
    email: "jane.smith@example.com",
    amount: 600,
    paymentMode: "UPI",
    status: "Pending",
  },
  {
    id: "64b9ee9f1c4e88f1a2b5c125",
    trackingId: "TRK123458",
    customerName: "Emily Davis",
    email: "emily.davis@example.com",
    amount: 450,
    paymentMode: "Debit Card",
    status: "Failed",
  },
  {
    id: "64b9ee9f1c4e88f1a2b5c126",
    trackingId: "TRK123459",
    customerName: "Michael Brown",
    email: "michael.brown@example.com",
    amount: 800,
    paymentMode: "Net Banking",
    status: "Success",
  },
  {
    id: "64b9ee9f1c4e88f1a2b5c127",
    trackingId: "TRK123460",
    customerName: "Sarah Wilson",
    email: "sarah.wilson@example.com",
    amount: 1000,
    paymentMode: "Wallet",
    status: "Success",
  },
  {
    id: "64b9ee9f1c4e88f1a2b5c128",
    trackingId: "TRK123461",
    customerName: "David Lee",
    email: "david.lee@example.com",
    amount: 700,
    paymentMode: "UPI",
    status: "Failed",
  },
  {
    id: "64b9ee9f1c4e88f1a2b5c129",
    trackingId: "TRK123462",
    customerName: "Sophia Martinez",
    email: "sophia.martinez@example.com",
    amount: 950,
    paymentMode: "Credit Card",
    status: "Pending",
  },
  {
    id: "64b9ee9f1c4e88f1a2b5c12a",
    trackingId: "TRK123463",
    customerName: "Tom Parker",
    email: "tom.parker@example.com",
    amount: 500,
    paymentMode: "Net Banking",
    status: "Success",
  },
  {
    id: "64b9ee9f1c4e88f1a2b5c12b",
    trackingId: "TRK123464",
    customerName: "Alice Brown",
    email: "alice.brown@example.com",
    amount: 600,
    paymentMode: "Debit Card",
    status: "Pending",
  },
  {
    id: "64b9ee9f1c4e88f1a2b5c12c",
    trackingId: "TRK123465",
    customerName: "Jack Taylor",
    email: "jack.taylor@example.com",
    amount: 1200,
    paymentMode: "Wallet",
    status: "Failed",
  },
  {
    id: "64b9ee9f1c4e88f1a2b5c12d",
    trackingId: "TRK123466",
    customerName: "Emma White",
    email: "emma.white@example.com",
    amount: 750,
    paymentMode: "UPI",
    status: "Success",
  },
  {
    id: "64b9ee9f1c4e88f1a2b5c12e",
    trackingId: "TRK123467",
    customerName: "Lucas Evans",
    email: "lucas.evans@example.com",
    amount: 300,
    paymentMode: "Credit Card",
    status: "Failed",
  },
  {
    id: "64b9ee9f1c4e88f1a2b5c12f",
    trackingId: "TRK123468",
    customerName: "Oliver Harris",
    email: "oliver.harris@example.com",
    amount: 1000,
    paymentMode: "Net Banking",
    status: "Success",
  },
  {
    id: "64b9ee9f1c4e88f1a2b5c130",
    trackingId: "TRK123469",
    customerName: "Mia Scott",
    email: "mia.scott@example.com",
    amount: 800,
    paymentMode: "Wallet",
    status: "Pending",
  },
  {
    id: "64b9ee9f1c4e88f1a2b5c131",
    trackingId: "TRK123470",
    customerName: "Natalie Green",
    email: "natalie.green@example.com",
    amount: 650,
    paymentMode: "Debit Card",
    status: "Success",
  },
];

